### ISSUE TITLE
A few quick comments

### ISSUE THREAD

**Issue by mpejcinovska** [shivankgoel003/Consulting-Services-Expenditure#1]
Some brief comments/suggestions for the final submission:

-	README file is missing LLM usage statement
-	Title could (and should) be reconsidered.
-	Pay attention to grammar and spelling. I recommend tightening the language. No need to narrate steps taken.
-	Data cleaning sections/descriptions belong in appendix. Keep only meaningful aspects of data processing which are crucial to reader understanding (e.g. note if a variable of interest was created as an aggregate of multiple other measures collected in the data).
-	Figures could be significantly improved.
- Perhaps reconsider section headings

**Comment by shivankgoel003** [comment]
All addresssed
